//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace apiFormTranslator.Model.SearchService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchServiceSoap", Namespace="http://www.prometric.com/webservices/intelitest")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseSynopsis))]
    public partial class SearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private User userField;
        
        private System.Threading.SendOrPostCallback ChildrenSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback JobSearchReturningSynopsisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ContentSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback ContentSearchReturningSynopsisPlusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListSearchReturningSynopsisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchService() {
            this.Url = global::apiFormTranslator.Model.Properties.Settings.Default.apiFormTranslator_Model_SearchService_SearchService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChildrenSearchCompletedEventHandler ChildrenSearchCompleted;
        
        /// <remarks/>
        public event JobSearchReturningSynopsisCompletedEventHandler JobSearchReturningSynopsisCompleted;
        
        /// <remarks/>
        public event ContentSearchCompletedEventHandler ContentSearchCompleted;
        
        /// <remarks/>
        public event ContentSearchReturningSynopsisPlusCompletedEventHandler ContentSearchReturningSynopsisPlusCompleted;
        
        /// <remarks/>
        public event ListSearchReturningSynopsisCompletedEventHandler ListSearchReturningSynopsisCompleted;
        
        /// <remarks/>
        public event ListSearchCompletedEventHandler ListSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ChildrenSearch", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchReference[] ChildrenSearch(string childType, string parentUUID, enumSearchDepth searchDepth, int timeout, string searchProviderType) {
            object[] results = this.Invoke("ChildrenSearch", new object[] {
                        childType,
                        parentUUID,
                        searchDepth,
                        timeout,
                        searchProviderType});
            return ((SearchReference[])(results[0]));
        }
        
        /// <remarks/>
        public void ChildrenSearchAsync(string childType, string parentUUID, enumSearchDepth searchDepth, int timeout, string searchProviderType) {
            this.ChildrenSearchAsync(childType, parentUUID, searchDepth, timeout, searchProviderType, null);
        }
        
        /// <remarks/>
        public void ChildrenSearchAsync(string childType, string parentUUID, enumSearchDepth searchDepth, int timeout, string searchProviderType, object userState) {
            if ((this.ChildrenSearchOperationCompleted == null)) {
                this.ChildrenSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChildrenSearchOperationCompleted);
            }
            this.InvokeAsync("ChildrenSearch", new object[] {
                        childType,
                        parentUUID,
                        searchDepth,
                        timeout,
                        searchProviderType}, this.ChildrenSearchOperationCompleted, userState);
        }
        
        private void OnChildrenSearchOperationCompleted(object arg) {
            if ((this.ChildrenSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChildrenSearchCompleted(this, new ChildrenSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/JobSearchReturningSynopsis", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FieldListSynopsis[] JobSearchReturningSynopsis(string strReferenceId, string strStartDate, string strEndDate, bool blnAllAvailableContexts) {
            object[] results = this.Invoke("JobSearchReturningSynopsis", new object[] {
                        strReferenceId,
                        strStartDate,
                        strEndDate,
                        blnAllAvailableContexts});
            return ((FieldListSynopsis[])(results[0]));
        }
        
        /// <remarks/>
        public void JobSearchReturningSynopsisAsync(string strReferenceId, string strStartDate, string strEndDate, bool blnAllAvailableContexts) {
            this.JobSearchReturningSynopsisAsync(strReferenceId, strStartDate, strEndDate, blnAllAvailableContexts, null);
        }
        
        /// <remarks/>
        public void JobSearchReturningSynopsisAsync(string strReferenceId, string strStartDate, string strEndDate, bool blnAllAvailableContexts, object userState) {
            if ((this.JobSearchReturningSynopsisOperationCompleted == null)) {
                this.JobSearchReturningSynopsisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJobSearchReturningSynopsisOperationCompleted);
            }
            this.InvokeAsync("JobSearchReturningSynopsis", new object[] {
                        strReferenceId,
                        strStartDate,
                        strEndDate,
                        blnAllAvailableContexts}, this.JobSearchReturningSynopsisOperationCompleted, userState);
        }
        
        private void OnJobSearchReturningSynopsisOperationCompleted(object arg) {
            if ((this.JobSearchReturningSynopsisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JobSearchReturningSynopsisCompleted(this, new JobSearchReturningSynopsisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ContentSearch", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchReference[] ContentSearch(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked) {
            object[] results = this.Invoke("ContentSearch", new object[] {
                        location,
                        locationSearchDepth,
                        contentTypes,
                        nameValues,
                        aliasValues,
                        attributes,
                        keywords,
                        comments,
                        statistics,
                        languages,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked});
            return ((SearchReference[])(results[0]));
        }
        
        /// <remarks/>
        public void ContentSearchAsync(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked) {
            this.ContentSearchAsync(location, locationSearchDepth, contentTypes, nameValues, aliasValues, attributes, keywords, comments, statistics, languages, createdOnValues, createdByValues, updatedOnValues, updatedByValues, includeLocked, includeUnlocked, null);
        }
        
        /// <remarks/>
        public void ContentSearchAsync(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked, 
                    object userState) {
            if ((this.ContentSearchOperationCompleted == null)) {
                this.ContentSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnContentSearchOperationCompleted);
            }
            this.InvokeAsync("ContentSearch", new object[] {
                        location,
                        locationSearchDepth,
                        contentTypes,
                        nameValues,
                        aliasValues,
                        attributes,
                        keywords,
                        comments,
                        statistics,
                        languages,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked}, this.ContentSearchOperationCompleted, userState);
        }
        
        private void OnContentSearchOperationCompleted(object arg) {
            if ((this.ContentSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ContentSearchCompleted(this, new ContentSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ContentSearchReturningSynopsisPlu" +
            "s", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FieldListSynopsis[] ContentSearchReturningSynopsisPlus(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked, 
                    string[] examUUIDForContentOutlineItems, 
                    string[] examUUIDForReferenceListItems) {
            object[] results = this.Invoke("ContentSearchReturningSynopsisPlus", new object[] {
                        location,
                        locationSearchDepth,
                        contentTypes,
                        nameValues,
                        aliasValues,
                        attributes,
                        keywords,
                        comments,
                        statistics,
                        languages,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked,
                        examUUIDForContentOutlineItems,
                        examUUIDForReferenceListItems});
            return ((FieldListSynopsis[])(results[0]));
        }
        
        /// <remarks/>
        public void ContentSearchReturningSynopsisPlusAsync(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked, 
                    string[] examUUIDForContentOutlineItems, 
                    string[] examUUIDForReferenceListItems) {
            this.ContentSearchReturningSynopsisPlusAsync(location, locationSearchDepth, contentTypes, nameValues, aliasValues, attributes, keywords, comments, statistics, languages, createdOnValues, createdByValues, updatedOnValues, updatedByValues, includeLocked, includeUnlocked, examUUIDForContentOutlineItems, examUUIDForReferenceListItems, null);
        }
        
        /// <remarks/>
        public void ContentSearchReturningSynopsisPlusAsync(
                    string location, 
                    enumSearchDepth locationSearchDepth, 
                    string[] contentTypes, 
                    StringSearch[] nameValues, 
                    StringSearch[] aliasValues, 
                    Attribute[] attributes, 
                    StringSearch[] keywords, 
                    StringSearch[] comments, 
                    Statistic[] statistics, 
                    StringSearch[] languages, 
                    StringSearch[] createdOnValues, 
                    StringSearch[] createdByValues, 
                    StringSearch[] updatedOnValues, 
                    StringSearch[] updatedByValues, 
                    bool includeLocked, 
                    bool includeUnlocked, 
                    string[] examUUIDForContentOutlineItems, 
                    string[] examUUIDForReferenceListItems, 
                    object userState) {
            if ((this.ContentSearchReturningSynopsisPlusOperationCompleted == null)) {
                this.ContentSearchReturningSynopsisPlusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnContentSearchReturningSynopsisPlusOperationCompleted);
            }
            this.InvokeAsync("ContentSearchReturningSynopsisPlus", new object[] {
                        location,
                        locationSearchDepth,
                        contentTypes,
                        nameValues,
                        aliasValues,
                        attributes,
                        keywords,
                        comments,
                        statistics,
                        languages,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked,
                        examUUIDForContentOutlineItems,
                        examUUIDForReferenceListItems}, this.ContentSearchReturningSynopsisPlusOperationCompleted, userState);
        }
        
        private void OnContentSearchReturningSynopsisPlusOperationCompleted(object arg) {
            if ((this.ContentSearchReturningSynopsisPlusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ContentSearchReturningSynopsisPlusCompleted(this, new ContentSearchReturningSynopsisPlusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ListSearchReturningSynopsis", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FieldListSynopsis[] ListSearchReturningSynopsis(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked) {
            object[] results = this.Invoke("ListSearchReturningSynopsis", new object[] {
                        location,
                        locationSearchDepth,
                        nameValues,
                        keywords,
                        attributes,
                        contains,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked});
            return ((FieldListSynopsis[])(results[0]));
        }
        
        /// <remarks/>
        public void ListSearchReturningSynopsisAsync(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked) {
            this.ListSearchReturningSynopsisAsync(location, locationSearchDepth, nameValues, keywords, attributes, contains, createdOnValues, createdByValues, updatedOnValues, updatedByValues, includeLocked, includeUnlocked, null);
        }
        
        /// <remarks/>
        public void ListSearchReturningSynopsisAsync(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked, object userState) {
            if ((this.ListSearchReturningSynopsisOperationCompleted == null)) {
                this.ListSearchReturningSynopsisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListSearchReturningSynopsisOperationCompleted);
            }
            this.InvokeAsync("ListSearchReturningSynopsis", new object[] {
                        location,
                        locationSearchDepth,
                        nameValues,
                        keywords,
                        attributes,
                        contains,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked}, this.ListSearchReturningSynopsisOperationCompleted, userState);
        }
        
        private void OnListSearchReturningSynopsisOperationCompleted(object arg) {
            if ((this.ListSearchReturningSynopsisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListSearchReturningSynopsisCompleted(this, new ListSearchReturningSynopsisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ListSearch", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchReference[] ListSearch(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked) {
            object[] results = this.Invoke("ListSearch", new object[] {
                        location,
                        locationSearchDepth,
                        nameValues,
                        keywords,
                        attributes,
                        contains,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked});
            return ((SearchReference[])(results[0]));
        }
        
        /// <remarks/>
        public void ListSearchAsync(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked) {
            this.ListSearchAsync(location, locationSearchDepth, nameValues, keywords, attributes, contains, createdOnValues, createdByValues, updatedOnValues, updatedByValues, includeLocked, includeUnlocked, null);
        }
        
        /// <remarks/>
        public void ListSearchAsync(string location, enumSearchDepth locationSearchDepth, StringSearch[] nameValues, StringSearch[] keywords, Attribute[] attributes, string[] contains, StringSearch[] createdOnValues, StringSearch[] createdByValues, StringSearch[] updatedOnValues, StringSearch[] updatedByValues, bool includeLocked, bool includeUnlocked, object userState) {
            if ((this.ListSearchOperationCompleted == null)) {
                this.ListSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListSearchOperationCompleted);
            }
            this.InvokeAsync("ListSearch", new object[] {
                        location,
                        locationSearchDepth,
                        nameValues,
                        keywords,
                        attributes,
                        contains,
                        createdOnValues,
                        createdByValues,
                        updatedOnValues,
                        updatedByValues,
                        includeLocked,
                        includeUnlocked}, this.ListSearchOperationCompleted, userState);
        }
        
        private void OnListSearchOperationCompleted(object arg) {
            if ((this.ListSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListSearchCompleted(this, new ListSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    [System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://www.prometric.com/webservices/intelitest", IsNullable=false)]
    public partial class User : System.Web.Services.Protocols.SoapHeader {
        
        private string currentContextIdField;
        
        private string userNameField;
        
        private string userIdField;
        
        private bool authenticatedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currentContextId {
            get {
                return this.currentContextIdField;
            }
            set {
                this.currentContextIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Statistic))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Attribute {
        
        private string nameField;
        
        private enumSearchType searchTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enumSearchType searchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public enum enumSearchType {
        
        /// <remarks/>
        Exact,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        Contains,
        
        /// <remarks/>
        IsTrue,
        
        /// <remarks/>
        IsFalse,
        
        /// <remarks/>
        Is,
        
        /// <remarks/>
        IsNot,
        
        /// <remarks/>
        LessThanOrEqualsTo,
        
        /// <remarks/>
        GreaterThanOrEqualsTo,
        
        /// <remarks/>
        Exists,
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        LaterThanOrEqualTo,
        
        /// <remarks/>
        EarlierThanOrEqualTo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Statistic : Attribute {
        
        private enumStatType statTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enumStatType statType {
            get {
                return this.statTypeField;
            }
            set {
                this.statTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public enum enumStatType {
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Form,
        
        /// <remarks/>
        FormItem,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class StringSearch {
        
        private string valueField;
        
        private enumSearchType searchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enumSearchType searchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Field {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldListSynopsis))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class BaseSynopsis {
        
        private string uuidField;
        
        private string referenceURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceURL {
            get {
                return this.referenceURLField;
            }
            set {
                this.referenceURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FieldListSynopsis : BaseSynopsis {
        
        private Field[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field")]
        public Field[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class SearchReference {
        
        private string nameField;
        
        private string valueField;
        
        private string refField;
        
        private string displayField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public enum enumSearchDepth {
        
        /// <remarks/>
        Shallow,
        
        /// <remarks/>
        Deep,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChildrenSearchCompletedEventHandler(object sender, ChildrenSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChildrenSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChildrenSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void JobSearchReturningSynopsisCompletedEventHandler(object sender, JobSearchReturningSynopsisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobSearchReturningSynopsisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JobSearchReturningSynopsisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldListSynopsis[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldListSynopsis[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ContentSearchCompletedEventHandler(object sender, ContentSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContentSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ContentSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ContentSearchReturningSynopsisPlusCompletedEventHandler(object sender, ContentSearchReturningSynopsisPlusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContentSearchReturningSynopsisPlusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ContentSearchReturningSynopsisPlusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldListSynopsis[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldListSynopsis[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListSearchReturningSynopsisCompletedEventHandler(object sender, ListSearchReturningSynopsisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListSearchReturningSynopsisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListSearchReturningSynopsisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldListSynopsis[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldListSynopsis[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListSearchCompletedEventHandler(object sender, ListSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchReference[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591