//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace apiFormTranslator.Model.ListService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ListServiceSoap", Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ListService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private User userField;
        
        private System.Threading.SendOrPostCallback CopyItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyExhibitListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemListContentHeaderSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePublicationListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadPublicationListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePublicationListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveExhibitListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadExhibitListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteExhibitListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ListService() {
            this.Url = global::apiFormTranslator.Model.Properties.Settings.Default.apiFormTranslator_Model_ListService_ListService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CopyItemListCompletedEventHandler CopyItemListCompleted;
        
        /// <remarks/>
        public event CopyExhibitListCompletedEventHandler CopyExhibitListCompleted;
        
        /// <remarks/>
        public event ItemListContentHeaderSearchCompletedEventHandler ItemListContentHeaderSearchCompleted;
        
        /// <remarks/>
        public event SaveItemListCompletedEventHandler SaveItemListCompleted;
        
        /// <remarks/>
        public event LoadItemListCompletedEventHandler LoadItemListCompleted;
        
        /// <remarks/>
        public event DeleteItemListCompletedEventHandler DeleteItemListCompleted;
        
        /// <remarks/>
        public event SavePublicationListCompletedEventHandler SavePublicationListCompleted;
        
        /// <remarks/>
        public event LoadPublicationListCompletedEventHandler LoadPublicationListCompleted;
        
        /// <remarks/>
        public event DeletePublicationListCompletedEventHandler DeletePublicationListCompleted;
        
        /// <remarks/>
        public event SaveExhibitListCompletedEventHandler SaveExhibitListCompleted;
        
        /// <remarks/>
        public event LoadExhibitListCompletedEventHandler LoadExhibitListCompleted;
        
        /// <remarks/>
        public event DeleteExhibitListCompletedEventHandler DeleteExhibitListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/CopyItemList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CopyItemList(string itemListId) {
            object[] results = this.Invoke("CopyItemList", new object[] {
                        itemListId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CopyItemListAsync(string itemListId) {
            this.CopyItemListAsync(itemListId, null);
        }
        
        /// <remarks/>
        public void CopyItemListAsync(string itemListId, object userState) {
            if ((this.CopyItemListOperationCompleted == null)) {
                this.CopyItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyItemListOperationCompleted);
            }
            this.InvokeAsync("CopyItemList", new object[] {
                        itemListId}, this.CopyItemListOperationCompleted, userState);
        }
        
        private void OnCopyItemListOperationCompleted(object arg) {
            if ((this.CopyItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyItemListCompleted(this, new CopyItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/CopyExhibitList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CopyExhibitList(string strExhibitListId, string strAssetCode) {
            object[] results = this.Invoke("CopyExhibitList", new object[] {
                        strExhibitListId,
                        strAssetCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CopyExhibitListAsync(string strExhibitListId, string strAssetCode) {
            this.CopyExhibitListAsync(strExhibitListId, strAssetCode, null);
        }
        
        /// <remarks/>
        public void CopyExhibitListAsync(string strExhibitListId, string strAssetCode, object userState) {
            if ((this.CopyExhibitListOperationCompleted == null)) {
                this.CopyExhibitListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyExhibitListOperationCompleted);
            }
            this.InvokeAsync("CopyExhibitList", new object[] {
                        strExhibitListId,
                        strAssetCode}, this.CopyExhibitListOperationCompleted, userState);
        }
        
        private void OnCopyExhibitListOperationCompleted(object arg) {
            if ((this.CopyExhibitListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyExhibitListCompleted(this, new CopyExhibitListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ItemListContentHeaderSearch", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchReference[] ItemListContentHeaderSearch(string strItemListId) {
            object[] results = this.Invoke("ItemListContentHeaderSearch", new object[] {
                        strItemListId});
            return ((SearchReference[])(results[0]));
        }
        
        /// <remarks/>
        public void ItemListContentHeaderSearchAsync(string strItemListId) {
            this.ItemListContentHeaderSearchAsync(strItemListId, null);
        }
        
        /// <remarks/>
        public void ItemListContentHeaderSearchAsync(string strItemListId, object userState) {
            if ((this.ItemListContentHeaderSearchOperationCompleted == null)) {
                this.ItemListContentHeaderSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemListContentHeaderSearchOperationCompleted);
            }
            this.InvokeAsync("ItemListContentHeaderSearch", new object[] {
                        strItemListId}, this.ItemListContentHeaderSearchOperationCompleted, userState);
        }
        
        private void OnItemListContentHeaderSearchOperationCompleted(object arg) {
            if ((this.ItemListContentHeaderSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemListContentHeaderSearchCompleted(this, new ItemListContentHeaderSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveItemList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemList SaveItemList(ItemList objItemList) {
            object[] results = this.Invoke("SaveItemList", new object[] {
                        objItemList});
            return ((ItemList)(results[0]));
        }
        
        /// <remarks/>
        public void SaveItemListAsync(ItemList objItemList) {
            this.SaveItemListAsync(objItemList, null);
        }
        
        /// <remarks/>
        public void SaveItemListAsync(ItemList objItemList, object userState) {
            if ((this.SaveItemListOperationCompleted == null)) {
                this.SaveItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveItemListOperationCompleted);
            }
            this.InvokeAsync("SaveItemList", new object[] {
                        objItemList}, this.SaveItemListOperationCompleted, userState);
        }
        
        private void OnSaveItemListOperationCompleted(object arg) {
            if ((this.SaveItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveItemListCompleted(this, new SaveItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadItemList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemList LoadItemList(string strItemListId) {
            object[] results = this.Invoke("LoadItemList", new object[] {
                        strItemListId});
            return ((ItemList)(results[0]));
        }
        
        /// <remarks/>
        public void LoadItemListAsync(string strItemListId) {
            this.LoadItemListAsync(strItemListId, null);
        }
        
        /// <remarks/>
        public void LoadItemListAsync(string strItemListId, object userState) {
            if ((this.LoadItemListOperationCompleted == null)) {
                this.LoadItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadItemListOperationCompleted);
            }
            this.InvokeAsync("LoadItemList", new object[] {
                        strItemListId}, this.LoadItemListOperationCompleted, userState);
        }
        
        private void OnLoadItemListOperationCompleted(object arg) {
            if ((this.LoadItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadItemListCompleted(this, new LoadItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteItemList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteItemList(string strItemListId) {
            object[] results = this.Invoke("DeleteItemList", new object[] {
                        strItemListId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteItemListAsync(string strItemListId) {
            this.DeleteItemListAsync(strItemListId, null);
        }
        
        /// <remarks/>
        public void DeleteItemListAsync(string strItemListId, object userState) {
            if ((this.DeleteItemListOperationCompleted == null)) {
                this.DeleteItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteItemListOperationCompleted);
            }
            this.InvokeAsync("DeleteItemList", new object[] {
                        strItemListId}, this.DeleteItemListOperationCompleted, userState);
        }
        
        private void OnDeleteItemListOperationCompleted(object arg) {
            if ((this.DeleteItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteItemListCompleted(this, new DeleteItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SavePublicationList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PublicationList SavePublicationList(PublicationList objPublicationList) {
            object[] results = this.Invoke("SavePublicationList", new object[] {
                        objPublicationList});
            return ((PublicationList)(results[0]));
        }
        
        /// <remarks/>
        public void SavePublicationListAsync(PublicationList objPublicationList) {
            this.SavePublicationListAsync(objPublicationList, null);
        }
        
        /// <remarks/>
        public void SavePublicationListAsync(PublicationList objPublicationList, object userState) {
            if ((this.SavePublicationListOperationCompleted == null)) {
                this.SavePublicationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePublicationListOperationCompleted);
            }
            this.InvokeAsync("SavePublicationList", new object[] {
                        objPublicationList}, this.SavePublicationListOperationCompleted, userState);
        }
        
        private void OnSavePublicationListOperationCompleted(object arg) {
            if ((this.SavePublicationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePublicationListCompleted(this, new SavePublicationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadPublicationList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PublicationList LoadPublicationList(string strPublicationListId) {
            object[] results = this.Invoke("LoadPublicationList", new object[] {
                        strPublicationListId});
            return ((PublicationList)(results[0]));
        }
        
        /// <remarks/>
        public void LoadPublicationListAsync(string strPublicationListId) {
            this.LoadPublicationListAsync(strPublicationListId, null);
        }
        
        /// <remarks/>
        public void LoadPublicationListAsync(string strPublicationListId, object userState) {
            if ((this.LoadPublicationListOperationCompleted == null)) {
                this.LoadPublicationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadPublicationListOperationCompleted);
            }
            this.InvokeAsync("LoadPublicationList", new object[] {
                        strPublicationListId}, this.LoadPublicationListOperationCompleted, userState);
        }
        
        private void OnLoadPublicationListOperationCompleted(object arg) {
            if ((this.LoadPublicationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadPublicationListCompleted(this, new LoadPublicationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeletePublicationList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeletePublicationList(string strPublicationListId) {
            object[] results = this.Invoke("DeletePublicationList", new object[] {
                        strPublicationListId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePublicationListAsync(string strPublicationListId) {
            this.DeletePublicationListAsync(strPublicationListId, null);
        }
        
        /// <remarks/>
        public void DeletePublicationListAsync(string strPublicationListId, object userState) {
            if ((this.DeletePublicationListOperationCompleted == null)) {
                this.DeletePublicationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePublicationListOperationCompleted);
            }
            this.InvokeAsync("DeletePublicationList", new object[] {
                        strPublicationListId}, this.DeletePublicationListOperationCompleted, userState);
        }
        
        private void OnDeletePublicationListOperationCompleted(object arg) {
            if ((this.DeletePublicationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePublicationListCompleted(this, new DeletePublicationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveExhibitList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExhibitIBList SaveExhibitList(ExhibitIBList objExhibitList) {
            object[] results = this.Invoke("SaveExhibitList", new object[] {
                        objExhibitList});
            return ((ExhibitIBList)(results[0]));
        }
        
        /// <remarks/>
        public void SaveExhibitListAsync(ExhibitIBList objExhibitList) {
            this.SaveExhibitListAsync(objExhibitList, null);
        }
        
        /// <remarks/>
        public void SaveExhibitListAsync(ExhibitIBList objExhibitList, object userState) {
            if ((this.SaveExhibitListOperationCompleted == null)) {
                this.SaveExhibitListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveExhibitListOperationCompleted);
            }
            this.InvokeAsync("SaveExhibitList", new object[] {
                        objExhibitList}, this.SaveExhibitListOperationCompleted, userState);
        }
        
        private void OnSaveExhibitListOperationCompleted(object arg) {
            if ((this.SaveExhibitListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveExhibitListCompleted(this, new SaveExhibitListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadExhibitList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExhibitIBList LoadExhibitList(string strExhibitListId) {
            object[] results = this.Invoke("LoadExhibitList", new object[] {
                        strExhibitListId});
            return ((ExhibitIBList)(results[0]));
        }
        
        /// <remarks/>
        public void LoadExhibitListAsync(string strExhibitListId) {
            this.LoadExhibitListAsync(strExhibitListId, null);
        }
        
        /// <remarks/>
        public void LoadExhibitListAsync(string strExhibitListId, object userState) {
            if ((this.LoadExhibitListOperationCompleted == null)) {
                this.LoadExhibitListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadExhibitListOperationCompleted);
            }
            this.InvokeAsync("LoadExhibitList", new object[] {
                        strExhibitListId}, this.LoadExhibitListOperationCompleted, userState);
        }
        
        private void OnLoadExhibitListOperationCompleted(object arg) {
            if ((this.LoadExhibitListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadExhibitListCompleted(this, new LoadExhibitListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteExhibitList", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteExhibitList(string strExhibitListId) {
            object[] results = this.Invoke("DeleteExhibitList", new object[] {
                        strExhibitListId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteExhibitListAsync(string strExhibitListId) {
            this.DeleteExhibitListAsync(strExhibitListId, null);
        }
        
        /// <remarks/>
        public void DeleteExhibitListAsync(string strExhibitListId, object userState) {
            if ((this.DeleteExhibitListOperationCompleted == null)) {
                this.DeleteExhibitListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteExhibitListOperationCompleted);
            }
            this.InvokeAsync("DeleteExhibitList", new object[] {
                        strExhibitListId}, this.DeleteExhibitListOperationCompleted, userState);
        }
        
        private void OnDeleteExhibitListOperationCompleted(object arg) {
            if ((this.DeleteExhibitListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteExhibitListCompleted(this, new DeleteExhibitListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    [System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://www.prometric.com/webservices/intelitest", IsNullable=false)]
    public partial class User : System.Web.Services.Protocols.SoapHeader {
        
        private string currentContextIdField;
        
        private string userNameField;
        
        private string userIdField;
        
        private bool authenticatedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currentContextId {
            get {
                return this.currentContextIdField;
            }
            set {
                this.currentContextIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Keyword {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ExhibitIBListElement {
        
        private string exhibitIBListElementIdField;
        
        private string assetIdField;
        
        private int ordinalField;
        
        private string captionField;
        
        private string assetMimeTypeField;
        
        /// <remarks/>
        public string ExhibitIBListElementId {
            get {
                return this.exhibitIBListElementIdField;
            }
            set {
                this.exhibitIBListElementIdField = value;
            }
        }
        
        /// <remarks/>
        public string AssetId {
            get {
                return this.assetIdField;
            }
            set {
                this.assetIdField = value;
            }
        }
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        public string AssetMimeType {
            get {
                return this.assetMimeTypeField;
            }
            set {
                this.assetMimeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ExhibitIBList {
        
        private string languageField;
        
        private string listNameField;
        
        private string listIdField;
        
        private string listMastercodeField;
        
        private string createdDatetimeField;
        
        private string createdUserField;
        
        private string modifiedDatetimeField;
        
        private string modifiedUserField;
        
        private string locationIdField;
        
        private string locationField;
        
        private string icscodeField;
        
        private string buttonCaptionField;
        
        private string buttonAssetIdField;
        
        private string buttonAssetNameField;
        
        private string stateField;
        
        private ExhibitIBListElement[] exhibitIBListElementsField;
        
        private Keyword[] keywordsField;
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string ListName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
            }
        }
        
        /// <remarks/>
        public string ListMastercode {
            get {
                return this.listMastercodeField;
            }
            set {
                this.listMastercodeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedDatetime {
            get {
                return this.createdDatetimeField;
            }
            set {
                this.createdDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedUser {
            get {
                return this.createdUserField;
            }
            set {
                this.createdUserField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDatetime {
            get {
                return this.modifiedDatetimeField;
            }
            set {
                this.modifiedDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public string LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Icscode {
            get {
                return this.icscodeField;
            }
            set {
                this.icscodeField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonCaption {
            get {
                return this.buttonCaptionField;
            }
            set {
                this.buttonCaptionField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonAssetId {
            get {
                return this.buttonAssetIdField;
            }
            set {
                this.buttonAssetIdField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonAssetName {
            get {
                return this.buttonAssetNameField;
            }
            set {
                this.buttonAssetNameField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public ExhibitIBListElement[] ExhibitIBListElements {
            get {
                return this.exhibitIBListElementsField;
            }
            set {
                this.exhibitIBListElementsField = value;
            }
        }
        
        /// <remarks/>
        public Keyword[] Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class PublicationListElement {
        
        private string publicationListElementIdField;
        
        private string publicationIdField;
        
        private int ordinalField;
        
        private bool openBookField;
        
        /// <remarks/>
        public string PublicationListElementId {
            get {
                return this.publicationListElementIdField;
            }
            set {
                this.publicationListElementIdField = value;
            }
        }
        
        /// <remarks/>
        public string PublicationId {
            get {
                return this.publicationIdField;
            }
            set {
                this.publicationIdField = value;
            }
        }
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public bool OpenBook {
            get {
                return this.openBookField;
            }
            set {
                this.openBookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class PublicationList {
        
        private string listNameField;
        
        private string listIdField;
        
        private string modifiedDatetimeField;
        
        private string modifiedUserField;
        
        private PublicationListElement[] publicationListElementsField;
        
        private string stateField;
        
        /// <remarks/>
        public string ListName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDatetime {
            get {
                return this.modifiedDatetimeField;
            }
            set {
                this.modifiedDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public PublicationListElement[] PublicationListElements {
            get {
                return this.publicationListElementsField;
            }
            set {
                this.publicationListElementsField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemListElement {
        
        private string itemListElementTypeField;
        
        private string statusField;
        
        private string itemListElementIdField;
        
        private string itemIdField;
        
        private int ordinalField;
        
        private int formWeightField;
        
        private bool selectableField;
        
        private bool equatorField;
        
        private bool scoredField;
        
        private string keyField;
        
        private bool newElementField;
        
        /// <remarks/>
        public string ItemListElementType {
            get {
                return this.itemListElementTypeField;
            }
            set {
                this.itemListElementTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ItemListElementId {
            get {
                return this.itemListElementIdField;
            }
            set {
                this.itemListElementIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public int FormWeight {
            get {
                return this.formWeightField;
            }
            set {
                this.formWeightField = value;
            }
        }
        
        /// <remarks/>
        public bool Selectable {
            get {
                return this.selectableField;
            }
            set {
                this.selectableField = value;
            }
        }
        
        /// <remarks/>
        public bool Equator {
            get {
                return this.equatorField;
            }
            set {
                this.equatorField = value;
            }
        }
        
        /// <remarks/>
        public bool Scored {
            get {
                return this.scoredField;
            }
            set {
                this.scoredField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public bool NewElement {
            get {
                return this.newElementField;
            }
            set {
                this.newElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemList {
        
        private string listNameField;
        
        private string listIdField;
        
        private string createdDatetimeField;
        
        private string createdUserField;
        
        private string modifiedDatetimeField;
        
        private string modifiedUserField;
        
        private string locationIdField;
        
        private string contentOutlineIdField;
        
        private string workflowIdField;
        
        private ItemListElement[] itemListElementsField;
        
        private string effectiveDateField;
        
        private string expirationDateField;
        
        private string stateField;
        
        /// <remarks/>
        public string ListName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedDatetime {
            get {
                return this.createdDatetimeField;
            }
            set {
                this.createdDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedUser {
            get {
                return this.createdUserField;
            }
            set {
                this.createdUserField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDatetime {
            get {
                return this.modifiedDatetimeField;
            }
            set {
                this.modifiedDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public string LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string ContentOutlineId {
            get {
                return this.contentOutlineIdField;
            }
            set {
                this.contentOutlineIdField = value;
            }
        }
        
        /// <remarks/>
        public string WorkflowId {
            get {
                return this.workflowIdField;
            }
            set {
                this.workflowIdField = value;
            }
        }
        
        /// <remarks/>
        public ItemListElement[] ItemListElements {
            get {
                return this.itemListElementsField;
            }
            set {
                this.itemListElementsField = value;
            }
        }
        
        /// <remarks/>
        public string EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class SearchReference {
        
        private string nameField;
        
        private string valueField;
        
        private string refField;
        
        private string displayField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CopyItemListCompletedEventHandler(object sender, CopyItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CopyExhibitListCompletedEventHandler(object sender, CopyExhibitListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyExhibitListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyExhibitListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ItemListContentHeaderSearchCompletedEventHandler(object sender, ItemListContentHeaderSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemListContentHeaderSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemListContentHeaderSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveItemListCompletedEventHandler(object sender, SaveItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoadItemListCompletedEventHandler(object sender, LoadItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteItemListCompletedEventHandler(object sender, DeleteItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SavePublicationListCompletedEventHandler(object sender, SavePublicationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePublicationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePublicationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublicationList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublicationList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoadPublicationListCompletedEventHandler(object sender, LoadPublicationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadPublicationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadPublicationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublicationList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublicationList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeletePublicationListCompletedEventHandler(object sender, DeletePublicationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePublicationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePublicationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveExhibitListCompletedEventHandler(object sender, SaveExhibitListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveExhibitListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveExhibitListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExhibitIBList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExhibitIBList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoadExhibitListCompletedEventHandler(object sender, LoadExhibitListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadExhibitListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadExhibitListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExhibitIBList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExhibitIBList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteExhibitListCompletedEventHandler(object sender, DeleteExhibitListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteExhibitListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteExhibitListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591