//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace apiFormTranslator.Model.ItemService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemServiceSoap", Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private User userField;
        
        private System.Threading.SendOrPostCallback SaveItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemIdsFromMasterCodesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ItemService() {
            this.Url = global::apiFormTranslator.Model.Properties.Settings.Default.apiFormTranslator_Model_ItemService_ItemService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveItemCompletedEventHandler SaveItemCompleted;
        
        /// <remarks/>
        public event DeleteItemCompletedEventHandler DeleteItemCompleted;
        
        /// <remarks/>
        public event LoadItemCompletedEventHandler LoadItemCompleted;
        
        /// <remarks/>
        public event CopyItemCompletedEventHandler CopyItemCompleted;
        
        /// <remarks/>
        public event ItemIdsFromMasterCodesCompletedEventHandler ItemIdsFromMasterCodesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveItem", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveItem(Item obj) {
            object[] results = this.Invoke("SaveItem", new object[] {
                        obj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveItemAsync(Item obj) {
            this.SaveItemAsync(obj, null);
        }
        
        /// <remarks/>
        public void SaveItemAsync(Item obj, object userState) {
            if ((this.SaveItemOperationCompleted == null)) {
                this.SaveItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveItemOperationCompleted);
            }
            this.InvokeAsync("SaveItem", new object[] {
                        obj}, this.SaveItemOperationCompleted, userState);
        }
        
        private void OnSaveItemOperationCompleted(object arg) {
            if ((this.SaveItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveItemCompleted(this, new SaveItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteItem", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteItem(string itemId) {
            this.Invoke("DeleteItem", new object[] {
                        itemId});
        }
        
        /// <remarks/>
        public void DeleteItemAsync(string itemId) {
            this.DeleteItemAsync(itemId, null);
        }
        
        /// <remarks/>
        public void DeleteItemAsync(string itemId, object userState) {
            if ((this.DeleteItemOperationCompleted == null)) {
                this.DeleteItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteItemOperationCompleted);
            }
            this.InvokeAsync("DeleteItem", new object[] {
                        itemId}, this.DeleteItemOperationCompleted, userState);
        }
        
        private void OnDeleteItemOperationCompleted(object arg) {
            if ((this.DeleteItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadItem", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Item LoadItem(string itemId) {
            object[] results = this.Invoke("LoadItem", new object[] {
                        itemId});
            return ((Item)(results[0]));
        }
        
        /// <remarks/>
        public void LoadItemAsync(string itemId) {
            this.LoadItemAsync(itemId, null);
        }
        
        /// <remarks/>
        public void LoadItemAsync(string itemId, object userState) {
            if ((this.LoadItemOperationCompleted == null)) {
                this.LoadItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadItemOperationCompleted);
            }
            this.InvokeAsync("LoadItem", new object[] {
                        itemId}, this.LoadItemOperationCompleted, userState);
        }
        
        private void OnLoadItemOperationCompleted(object arg) {
            if ((this.LoadItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadItemCompleted(this, new LoadItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/CopyItem", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CopyItem(string sourceId, string destinationMastercode, ItemCopyType copyType) {
            object[] results = this.Invoke("CopyItem", new object[] {
                        sourceId,
                        destinationMastercode,
                        copyType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CopyItemAsync(string sourceId, string destinationMastercode, ItemCopyType copyType) {
            this.CopyItemAsync(sourceId, destinationMastercode, copyType, null);
        }
        
        /// <remarks/>
        public void CopyItemAsync(string sourceId, string destinationMastercode, ItemCopyType copyType, object userState) {
            if ((this.CopyItemOperationCompleted == null)) {
                this.CopyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyItemOperationCompleted);
            }
            this.InvokeAsync("CopyItem", new object[] {
                        sourceId,
                        destinationMastercode,
                        copyType}, this.CopyItemOperationCompleted, userState);
        }
        
        private void OnCopyItemOperationCompleted(object arg) {
            if ((this.CopyItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyItemCompleted(this, new CopyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/ItemIdsFromMasterCodes", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ItemIdsFromMasterCodes(string[] masterCodes) {
            object[] results = this.Invoke("ItemIdsFromMasterCodes", new object[] {
                        masterCodes});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ItemIdsFromMasterCodesAsync(string[] masterCodes) {
            this.ItemIdsFromMasterCodesAsync(masterCodes, null);
        }
        
        /// <remarks/>
        public void ItemIdsFromMasterCodesAsync(string[] masterCodes, object userState) {
            if ((this.ItemIdsFromMasterCodesOperationCompleted == null)) {
                this.ItemIdsFromMasterCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemIdsFromMasterCodesOperationCompleted);
            }
            this.InvokeAsync("ItemIdsFromMasterCodes", new object[] {
                        masterCodes}, this.ItemIdsFromMasterCodesOperationCompleted, userState);
        }
        
        private void OnItemIdsFromMasterCodesOperationCompleted(object arg) {
            if ((this.ItemIdsFromMasterCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemIdsFromMasterCodesCompleted(this, new ItemIdsFromMasterCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    [System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://www.prometric.com/webservices/intelitest", IsNullable=false)]
    public partial class User : System.Web.Services.Protocols.SoapHeader {
        
        private string currentContextIdField;
        
        private string userNameField;
        
        private string userIdField;
        
        private bool authenticatedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currentContextId {
            get {
                return this.currentContextIdField;
            }
            set {
                this.currentContextIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemOption {
        
        private string optionTextField;
        
        private uint sequenceField;
        
        private decimal weightField;
        
        private bool keyField;
        
        private string rationaleField;
        
        /// <remarks/>
        public string OptionText {
            get {
                return this.optionTextField;
            }
            set {
                this.optionTextField = value;
            }
        }
        
        /// <remarks/>
        public uint Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public bool Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Rationale {
            get {
                return this.rationaleField;
            }
            set {
                this.rationaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeFormShortAnswerTextBox))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeFormEssayTextBox))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public abstract partial class FreeFormTextBox {
        
        private int maxResponseLengthField;
        
        private int widthField;
        
        private int heightField;
        
        private string fontTypeField;
        
        private int fontSizeField;
        
        private int backgroundColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxResponseLength {
            get {
                return this.maxResponseLengthField;
            }
            set {
                this.maxResponseLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fontType {
            get {
                return this.fontTypeField;
            }
            set {
                this.fontTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int fontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int backgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FreeFormShortAnswerTextBox : FreeFormTextBox {
        
        private string[] correctExpressionsField;
        
        private bool isMatchedField;
        
        private bool ignoreCaseField;
        
        private bool ignoreWhiteSpaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("correctExpression")]
        public string[] correctExpressions {
            get {
                return this.correctExpressionsField;
            }
            set {
                this.correctExpressionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isMatched {
            get {
                return this.isMatchedField;
            }
            set {
                this.isMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ignoreCase {
            get {
                return this.ignoreCaseField;
            }
            set {
                this.ignoreCaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ignoreWhiteSpace {
            get {
                return this.ignoreWhiteSpaceField;
            }
            set {
                this.ignoreWhiteSpaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FreeFormEssayTextBox : FreeFormTextBox {
        
        private bool isJudgedField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isJudged {
            get {
                return this.isJudgedField;
            }
            set {
                this.isJudgedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class CustomAttribute {
        
        private string idField;
        
        private string internalNameField;
        
        private string displayNameField;
        
        private string displayValueField;
        
        private int ordinalField;
        
        private System.DateTime utcCreateDateTimeField;
        
        private System.DateTime utcModifiedDateTimeField;
        
        private string createUserField;
        
        private string modifiedUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string internalName {
            get {
                return this.internalNameField;
            }
            set {
                this.internalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayValue {
            get {
                return this.displayValueField;
            }
            set {
                this.displayValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime utcCreateDateTime {
            get {
                return this.utcCreateDateTimeField;
            }
            set {
                this.utcCreateDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime utcModifiedDateTime {
            get {
                return this.utcModifiedDateTimeField;
            }
            set {
                this.utcModifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string createUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Keyword {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ContentKeyword {
        
        private Keyword[] keywordsField;
        
        private string contentIdField;
        
        private bool overwriteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("keyword")]
        public Keyword[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class AssetListStructure {
        
        private string assetidField;
        
        private string assettagField;
        
        private string assettitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetid {
            get {
                return this.assetidField;
            }
            set {
                this.assetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assettag {
            get {
                return this.assettagField;
            }
            set {
                this.assettagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assettitle {
            get {
                return this.assettitleField;
            }
            set {
                this.assettitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCQMR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCQSR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCMRD))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemHotSpot))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemDragAndDrop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemSetHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PBTCoversheet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemFreeForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemFreeFormEssay))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemFreeFormShortAnswer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Item {
        
        private AssetListStructure[] listOfAssetsField;
        
        private ContentKeyword keywordsField;
        
        private CustomAttribute[] customAttributesField;
        
        private decimal iRTAParamField;
        
        private decimal iRTBParamField;
        
        private decimal iRTCParamField;
        
        private decimal iRTAParamStdErrField;
        
        private decimal iRTBParamStdErrField;
        
        private decimal iRTCParamStdErrField;
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string revisionField;
        
        private float versionField;
        
        private string typeIdField;
        
        private string typeNameField;
        
        private string owneridField;
        
        private bool lockedField;
        
        private string platformField;
        
        private string layoutidField;
        
        private bool utd_promptrequiredField;
        
        private string promptField;
        
        private bool utd_scoredField;
        
        private string stateField;
        
        private string statusField;
        
        private string folderuuidField;
        
        private string editornotesField;
        
        private string languageField;
        
        private string cognitivelevelField;
        
        private string createdonField;
        
        private string createdbyField;
        
        private string updatedonField;
        
        private string updatedbyField;
        
        private string importlabelField;
        
        private string importdateField;
        
        private bool utd_skipallowedField;
        
        private bool prometricownedField;
        
        private string rawKeywordDelimitedStringField;
        
        private string mastercodeField;
        
        private string altIDField;
        
        private string itemWriterField;
        
        private string icscodeField;
        
        private string importcodeField;
        
        private bool negativestemField;
        
        private bool romannumeralField;
        
        private bool goalactionField;
        
        private string difficultyField;
        
        private string multikeyField;
        
        private bool openbookindicatorField;
        
        private string estimateddifficultyField;
        
        private string itemtypecssField;
        
        private string itemcontentcssField;
        
        private bool itempresentationindicatorField;
        
        /// <remarks/>
        public AssetListStructure[] ListOfAssets {
            get {
                return this.listOfAssetsField;
            }
            set {
                this.listOfAssetsField = value;
            }
        }
        
        /// <remarks/>
        public ContentKeyword Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttribute[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTAParam {
            get {
                return this.iRTAParamField;
            }
            set {
                this.iRTAParamField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTBParam {
            get {
                return this.iRTBParamField;
            }
            set {
                this.iRTBParamField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTCParam {
            get {
                return this.iRTCParamField;
            }
            set {
                this.iRTCParamField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTAParamStdErr {
            get {
                return this.iRTAParamStdErrField;
            }
            set {
                this.iRTAParamStdErrField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTBParamStdErr {
            get {
                return this.iRTBParamStdErrField;
            }
            set {
                this.iRTBParamStdErrField = value;
            }
        }
        
        /// <remarks/>
        public decimal IRTCParamStdErr {
            get {
                return this.iRTCParamStdErrField;
            }
            set {
                this.iRTCParamStdErrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ownerid {
            get {
                return this.owneridField;
            }
            set {
                this.owneridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string layoutid {
            get {
                return this.layoutidField;
            }
            set {
                this.layoutidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool utd_promptrequired {
            get {
                return this.utd_promptrequiredField;
            }
            set {
                this.utd_promptrequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prompt {
            get {
                return this.promptField;
            }
            set {
                this.promptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool utd_scored {
            get {
                return this.utd_scoredField;
            }
            set {
                this.utd_scoredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folderuuid {
            get {
                return this.folderuuidField;
            }
            set {
                this.folderuuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string editornotes {
            get {
                return this.editornotesField;
            }
            set {
                this.editornotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cognitivelevel {
            get {
                return this.cognitivelevelField;
            }
            set {
                this.cognitivelevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string createdon {
            get {
                return this.createdonField;
            }
            set {
                this.createdonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string createdby {
            get {
                return this.createdbyField;
            }
            set {
                this.createdbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedon {
            get {
                return this.updatedonField;
            }
            set {
                this.updatedonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string importlabel {
            get {
                return this.importlabelField;
            }
            set {
                this.importlabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string importdate {
            get {
                return this.importdateField;
            }
            set {
                this.importdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool utd_skipallowed {
            get {
                return this.utd_skipallowedField;
            }
            set {
                this.utd_skipallowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool prometricowned {
            get {
                return this.prometricownedField;
            }
            set {
                this.prometricownedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rawKeywordDelimitedString {
            get {
                return this.rawKeywordDelimitedStringField;
            }
            set {
                this.rawKeywordDelimitedStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mastercode {
            get {
                return this.mastercodeField;
            }
            set {
                this.mastercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AltID {
            get {
                return this.altIDField;
            }
            set {
                this.altIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemWriter {
            get {
                return this.itemWriterField;
            }
            set {
                this.itemWriterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icscode {
            get {
                return this.icscodeField;
            }
            set {
                this.icscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string importcode {
            get {
                return this.importcodeField;
            }
            set {
                this.importcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool negativestem {
            get {
                return this.negativestemField;
            }
            set {
                this.negativestemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool romannumeral {
            get {
                return this.romannumeralField;
            }
            set {
                this.romannumeralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool goalaction {
            get {
                return this.goalactionField;
            }
            set {
                this.goalactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string multikey {
            get {
                return this.multikeyField;
            }
            set {
                this.multikeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool openbookindicator {
            get {
                return this.openbookindicatorField;
            }
            set {
                this.openbookindicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estimateddifficulty {
            get {
                return this.estimateddifficultyField;
            }
            set {
                this.estimateddifficultyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string itemtypecss {
            get {
                return this.itemtypecssField;
            }
            set {
                this.itemtypecssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string itemcontentcss {
            get {
                return this.itemcontentcssField;
            }
            set {
                this.itemcontentcssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool itempresentationindicator {
            get {
                return this.itempresentationindicatorField;
            }
            set {
                this.itempresentationindicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCQMR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCQSR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemMCMRD))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemMCQ : Item {
        
        private ItemOption[] listOfOptionsField;
        
        private string headerField;
        
        private string stemField;
        
        private string stemrationaleField;
        
        private bool utd_autopromptField;
        
        private string utd_buttonimageField;
        
        private string utd_buttonimagepressField;
        
        private string utd_buttonalttextField;
        
        private string utd_buttonaltpresstextField;
        
        private bool utd_enablestrikeoutField;
        
        private string optionDesignatorField;
        
        private string optionsorttypeField;
        
        /// <remarks/>
        public ItemOption[] ListOfOptions {
            get {
                return this.listOfOptionsField;
            }
            set {
                this.listOfOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stem {
            get {
                return this.stemField;
            }
            set {
                this.stemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stemrationale {
            get {
                return this.stemrationaleField;
            }
            set {
                this.stemrationaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool utd_autoprompt {
            get {
                return this.utd_autopromptField;
            }
            set {
                this.utd_autopromptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_buttonimage {
            get {
                return this.utd_buttonimageField;
            }
            set {
                this.utd_buttonimageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_buttonimagepress {
            get {
                return this.utd_buttonimagepressField;
            }
            set {
                this.utd_buttonimagepressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_buttonalttext {
            get {
                return this.utd_buttonalttextField;
            }
            set {
                this.utd_buttonalttextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_buttonaltpresstext {
            get {
                return this.utd_buttonaltpresstextField;
            }
            set {
                this.utd_buttonaltpresstextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool utd_enablestrikeout {
            get {
                return this.utd_enablestrikeoutField;
            }
            set {
                this.utd_enablestrikeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OptionDesignator {
            get {
                return this.optionDesignatorField;
            }
            set {
                this.optionDesignatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string optionsorttype {
            get {
                return this.optionsorttypeField;
            }
            set {
                this.optionsorttypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemMCQMR : ItemMCQ {
        
        private string minResponsesField;
        
        private string maxResponsesField;
        
        private string uTD_TooManyField;
        
        private string uTD_TooFewField;
        
        private string uTD_MinScoreField;
        
        private string uTD_MaxScoreField;
        
        private string minResponseMsgField;
        
        private string maxResponseMsgField;
        
        /// <remarks/>
        public string MinResponses {
            get {
                return this.minResponsesField;
            }
            set {
                this.minResponsesField = value;
            }
        }
        
        /// <remarks/>
        public string MaxResponses {
            get {
                return this.maxResponsesField;
            }
            set {
                this.maxResponsesField = value;
            }
        }
        
        /// <remarks/>
        public string UTD_TooMany {
            get {
                return this.uTD_TooManyField;
            }
            set {
                this.uTD_TooManyField = value;
            }
        }
        
        /// <remarks/>
        public string UTD_TooFew {
            get {
                return this.uTD_TooFewField;
            }
            set {
                this.uTD_TooFewField = value;
            }
        }
        
        /// <remarks/>
        public string UTD_MinScore {
            get {
                return this.uTD_MinScoreField;
            }
            set {
                this.uTD_MinScoreField = value;
            }
        }
        
        /// <remarks/>
        public string UTD_MaxScore {
            get {
                return this.uTD_MaxScoreField;
            }
            set {
                this.uTD_MaxScoreField = value;
            }
        }
        
        /// <remarks/>
        public string MinResponseMsg {
            get {
                return this.minResponseMsgField;
            }
            set {
                this.minResponseMsgField = value;
            }
        }
        
        /// <remarks/>
        public string MaxResponseMsg {
            get {
                return this.maxResponseMsgField;
            }
            set {
                this.maxResponseMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemMCQSR : ItemMCQ {
        
        private string keyField;
        
        private string weightField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemMCMRD : ItemMCQ {
        
        private bool dichotomousField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dichotomous {
            get {
                return this.dichotomousField;
            }
            set {
                this.dichotomousField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemHotSpot : Item {
        
        private string polygonresultsField;
        
        private string assetbackgroundField;
        
        private string hotspotstemField;
        
        private string hotspotstemrationaleField;
        
        private string hsmultikeyField;
        
        private string maxresponsesField;
        
        private string minresponsesField;
        
        private string minresponsemessageField;
        
        private string maxresponsemessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string polygonresults {
            get {
                return this.polygonresultsField;
            }
            set {
                this.polygonresultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetbackground {
            get {
                return this.assetbackgroundField;
            }
            set {
                this.assetbackgroundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotspotstem {
            get {
                return this.hotspotstemField;
            }
            set {
                this.hotspotstemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotspotstemrationale {
            get {
                return this.hotspotstemrationaleField;
            }
            set {
                this.hotspotstemrationaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hsmultikey {
            get {
                return this.hsmultikeyField;
            }
            set {
                this.hsmultikeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxresponses {
            get {
                return this.maxresponsesField;
            }
            set {
                this.maxresponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minresponses {
            get {
                return this.minresponsesField;
            }
            set {
                this.minresponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minresponsemessage {
            get {
                return this.minresponsemessageField;
            }
            set {
                this.minresponsemessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxresponsemessage {
            get {
                return this.maxresponsemessageField;
            }
            set {
                this.maxresponsemessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemDragAndDrop : Item {
        
        private string draganddropxmlField;
        
        private string stemField;
        
        private string stemrationaleField;
        
        private string maxresponsesField;
        
        private string minresponsesField;
        
        private string minresponsemessageField;
        
        private string maxresponsemessageField;
        
        private string utd_maxscoreField;
        
        private string utd_minscoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string draganddropxml {
            get {
                return this.draganddropxmlField;
            }
            set {
                this.draganddropxmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stem {
            get {
                return this.stemField;
            }
            set {
                this.stemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stemrationale {
            get {
                return this.stemrationaleField;
            }
            set {
                this.stemrationaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxresponses {
            get {
                return this.maxresponsesField;
            }
            set {
                this.maxresponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minresponses {
            get {
                return this.minresponsesField;
            }
            set {
                this.minresponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minresponsemessage {
            get {
                return this.minresponsemessageField;
            }
            set {
                this.minresponsemessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxresponsemessage {
            get {
                return this.maxresponsemessageField;
            }
            set {
                this.maxresponsemessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_maxscore {
            get {
                return this.utd_maxscoreField;
            }
            set {
                this.utd_maxscoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utd_minscore {
            get {
                return this.utd_minscoreField;
            }
            set {
                this.utd_minscoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemSetHeader : Item {
        
        private string setheaderField;
        
        private string setheaderrationaleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string setheader {
            get {
                return this.setheaderField;
            }
            set {
                this.setheaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string setheaderrationale {
            get {
                return this.setheaderrationaleField;
            }
            set {
                this.setheaderrationaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class PBTCoversheet : Item {
        
        private string headerField;
        
        private string footerField;
        
        private string testdirectionsField;
        
        private string maincoversheettextField;
        
        private string coversheetnameField;
        
        private bool pagenumberingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footer {
            get {
                return this.footerField;
            }
            set {
                this.footerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testdirections {
            get {
                return this.testdirectionsField;
            }
            set {
                this.testdirectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maincoversheettext {
            get {
                return this.maincoversheettextField;
            }
            set {
                this.maincoversheettextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coversheetname {
            get {
                return this.coversheetnameField;
            }
            set {
                this.coversheetnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool pagenumbering {
            get {
                return this.pagenumberingField;
            }
            set {
                this.pagenumberingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemFreeFormEssay))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemFreeFormShortAnswer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public abstract partial class ItemFreeForm : Item {
        
        private FreeFormTextBox[] textBoxesField;
        
        private string stemField;
        
        private string stemRationaleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("textBox")]
        public FreeFormTextBox[] textBoxes {
            get {
                return this.textBoxesField;
            }
            set {
                this.textBoxesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stem {
            get {
                return this.stemField;
            }
            set {
                this.stemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stemRationale {
            get {
                return this.stemRationaleField;
            }
            set {
                this.stemRationaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemFreeFormEssay : ItemFreeForm {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class ItemFreeFormShortAnswer : ItemFreeForm {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public enum ItemCopyType {
        
        /// <remarks/>
        LANGUAGE,
        
        /// <remarks/>
        CHILD,
        
        /// <remarks/>
        SIBLING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveItemCompletedEventHandler(object sender, SaveItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoadItemCompletedEventHandler(object sender, LoadItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Item Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Item)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CopyItemCompletedEventHandler(object sender, CopyItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ItemIdsFromMasterCodesCompletedEventHandler(object sender, ItemIdsFromMasterCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemIdsFromMasterCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemIdsFromMasterCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591